from django.db import models

# Create your models here.
class Esm(models.Model):
    orderDate = models.DateField()
    customerId = models.CharField(null=True, max_length=255)
    mallId = models.CharField(null=True, max_length=255)
    orderNum = models.IntegerField()
    productNum = models.IntegerField(null=True)
    productName = models.CharField( max_length=255)
    orderAmount = models.IntegerField()
    orderOption = models.CharField(null=True,max_length=255)
    additionalConfig = models.CharField(null=True,max_length=255)
    orderGift = models.CharField(null=True,max_length=255)
    orderGiftCode = models.IntegerField(null=True)
    orderBonusCode = models.IntegerField(null=True)
    unitPrice = models.IntegerField()
    unitSold = models.IntegerField()
    sellerCode = models.IntegerField()
    sellerDetailCode = models.IntegerField(null=True)
    customerCellNum = models.IntegerField()
    customerPhoneNum = models.IntegerField()
    recipientName = models.TextField(max_length=255)
    recipientCellNum = models.IntegerField()
    recipientPhoneNum = models.IntegerField()
    recipientCustomsInfo = models.TextField(null=True,max_length=255)
    postCode = models.IntegerField()
    recipientAddress = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    shippingFeeType = models.TextField(max_length=255)
    shippingFee = models.TextField(max_length=255)
    shippingNum = models.IntegerField()
    shippingPolicy = models.TextField(max_length=255)
    skuNum = models.IntegerField(null=True)
    deliveryStore = models.TextField(null=True,max_length=255)
    saleType = models.TextField(null=True,max_length=255)
    orderType = models.TextField(null=True,max_length=255)
    shoppingBasketNum = models.IntegerField()
    orderPaymentCompleteDate = models.DateField(max_length=255)
    settlementAmount = models.IntegerField()
    serviceUsageFee = models.IntegerField()
    sellerCouponSale = models.IntegerField()
    couponAppliedAmount = models.IntegerField()
    auctionVipDiscount = models.IntegerField()
    multiplePurchasesDiscount = models.IntegerField()
    scount = models.IntegerField()
    smileCash = models.IntegerField()
    sellerCash = models.IntegerField()
    affiliatedCompany = models.TextField(null=True,max_length=255)
    shopSite = models.TextField(max_length=255)



