# Generated by Django 3.2.9 on 2021-11-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('customerId', models.CharField(max_length=255, null=True)),
                ('MallId', models.CharField(max_length=255, null=True)),
                ('orderNum', models.IntegerField()),
                ('productNum', models.IntegerField(null=True)),
                ('productName', models.CharField(max_length=255)),
                ('orderAmount', models.IntegerField()),
                ('orderOption', models.CharField(max_length=255, null=True)),
                ('additionalConfig', models.CharField(max_length=255, null=True)),
                ('orderGift', models.CharField(max_length=255, null=True)),
                ('orderGiftCode', models.IntegerField(null=True)),
                ('orderBonusCode', models.IntegerField(null=True)),
                ('unitPrice', models.IntegerField()),
                ('unitSold', models.IntegerField()),
                ('sellerCode', models.IntegerField()),
                ('sellerDetailCode', models.IntegerField(null=True)),
                ('customerCellNum', models.IntegerField()),
                ('customerPhoneNum', models.IntegerField()),
                ('recipientName', models.TextField(max_length=255)),
                ('recipientCellNum', models.IntegerField()),
                ('recipientPhoneNum', models.IntegerField()),
                ('recipientCustomsInfo', models.TextField(max_length=255, null=True)),
                ('postCode', models.IntegerField()),
                ('recipientAddress', models.TextField(max_length=255)),
                ('orderRequirements', models.TextField(max_length=255)),
                ('shippingFeeType', models.TextField(max_length=255)),
                ('shippingFee', models.TextField(max_length=255)),
                ('shippingNum', models.IntegerField()),
                ('shippingPolicy', models.TextField(max_length=255)),
                ('skuNum', models.IntegerField(null=True)),
                ('deliveryStore', models.TextField(max_length=255, null=True)),
                ('saleType', models.TextField(max_length=255, null=True)),
                ('orderType', models.TextField(max_length=255, null=True)),
                ('shoppingBasketNum', models.IntegerField()),
                ('orderPaymentCompleteDate', models.DateField(max_length=255)),
                ('settlementAmount', models.IntegerField()),
                ('serviceUsageFee', models.IntegerField()),
                ('sellerCouponSale', models.IntegerField()),
                ('couponAppliedAmount', models.IntegerField()),
                ('auctionVipDiscount', models.IntegerField()),
                ('multiplePurchasesDiscount', models.IntegerField()),
                ('scount', models.IntegerField()),
                ('smileCash', models.IntegerField()),
                ('sellerCash', models.IntegerField()),
                ('affiliatedCompany', models.TextField(max_length=255, null=True)),
                ('shopSite', models.TextField(max_length=255)),
            ],
        ),
    ]
