# Generated by Django 3.2.9 on 2021-11-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionNumber', models.IntegerField()),
                ('orderNum', models.IntegerField()),
            ],
        ),
    ]
