# Generated by Django 3.2.9 on 2021-11-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0002_tmon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esm',
            old_name='MallId',
            new_name='Id',
        ),
    ]
