# Generated by Django 3.2.9 on 2021-11-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0003_rename_mallid_esm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esm',
            name='scount',
        ),
    ]
