from django.db import models


# Create your models here.
class Coupang(models.Model):
    deliveredDate = models.TextField(null=True, max_length=255)
    separated = models.TextField(null=True)
    remoteAreaCharge = models.IntegerField(null=True)
    shippingNum = models.IntegerField()
    parentShipmentBoxId = models.IntegerField()
    orderNum = models.TextField(max_length=255)
    shippingBundleId = models.TextField(max_length=255)
    customerIdNum = models.IntegerField()
    customerName = models.TextField(max_length=255)
    shippingFee = models.IntegerField()
    invoiceNumber = models.TextField(null=True)
    deliveryStatusCode = models.TextField(null=True)
    postCode = models.IntegerField()
    orderRequirements = models.TextField()
    recipientAddressOne = models.TextField()
    recipientAddressTwo = models.TextField()
    customerCellNum2 = models.TextField(null=True, max_length=255)
    customerPhoneNum = models.TextField(null=True, max_length=255)
    recipientName = models.TextField(max_length=255)
    deliverCode = models.TextField(max_length=255)
    deliverName = models.TextField(max_length=255)
    trackingUrl = models.TextField(max_length=255)
    pcpCourier = models.TextField(max_length=255)
    pcpContractType = models.TextField(max_length=255)
    pcpDelivering = models.TextField(max_length=255)
    pcpDeliverable = models.TextField(max_length=255)
    productShipmentType = models.TextField(max_length=255)
    errorType = models.TextField(max_length=255)
    errorMessage = models.TextField(max_length=255)
    ableSplitShipping = models.TextField(max_length=255)
    updatedPlannedShippingDate = models.TextField(max_length=255)
    coupangFCSellerSendTo = models.TextField(max_length=255)
    logistics = models.TextField(max_length=255)
    recipientAddress = models.TextField(max_length=255)
    giveSecondBool = models.TextField(max_length=255)
    remoteAreaDelivery = models.TextField(max_length=255)
    hasMultipleItems = models.TextField(max_length=255)
    confirmed = models.TextField(max_length=255)
    createdAt = models.TextField(max_length=255)
    modifiedAt = models.TextField(max_length=255)
    customerCellNum1 = models.IntegerField()
    customerCellNum = models.IntegerField()
    safeNumber = models.IntegerField()
    safeNumberSrl = models.TextField(max_length=255)
    mallName = models.TextField(max_length=255,default='쿠팡')

    def __str__(self):
        return " 주문자 : "+self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
       ordering = ['-id']

class Interpark(models.Model):
    orderDate = models.DateField()
    recipientAddress = models.TextField(max_length=255)
    serviceUsageFee = models.TextField(null=True, max_length=255)
    callsafeYn = models.TextField(max_length=255)
    clmreqCnt = models.IntegerField()
    crmCouponDiscountAmount = models.IntegerField()
    currentOrdclmprdStat = models.IntegerField()
    currentOrdclmprdStatNm = models.TextField(max_length=255)
    shippingFee = models.TextField(max_length=255)
    orderAmount1 = models.TextField(max_length=255)
    orderType = models.TextField(max_length=255)
    delvAttbt = models.IntegerField()
    delvAttbtNm = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    delvWhDt = models.TextField(max_length=255)
    delvwhOrdNo = models.TextField(max_length=255)
    delvwhPreDate = models.TextField(max_length=255)
    dtlAddr = models.TextField(max_length=255)
    dtlAddrDoro = models.TextField(max_length=255)
    couponAppliedAmount = models.TextField(max_length=255)
    discountAmount = models.IntegerField()
    expectedSellingFee = models.IntegerField()
    expectedSettlementAmt = models.IntegerField()
    sellerCode = models.IntegerField()
    externalPrdNo = models.IntegerField()
    feeRate = models.IntegerField()
    hdelvMafcEntrNoDefault = models.IntegerField()
    inpkCouponDiscountAmount = models.IntegerField()
    interestFreeFee = models.IntegerField()
    ipointDcAmt = models.IntegerField()
    ipointFee = models.IntegerField()
    manufacture= models.TextField(max_length=255)
    marginRate = models.TextField(max_length=255)
    modDelvwhPreDate = models.TextField(max_length=255)
    modDelvwhPreDateYn = models.TextField(max_length=255)
    odpDtlAddr= models.TextField(max_length=255)
    odpDtlAddrDoro= models.TextField(max_length=255)
    odpZipAddr= models.TextField(max_length=255)
    odpZipAddrDoro= models.TextField(max_length=255)
    odpZipNo= models.TextField(max_length=255)
    odpZipNoDoro= models.TextField(max_length=255)
    optFnm = models.TextField(max_length=255)
    optParentSeq = models.IntegerField()
    optPrdTp = models.IntegerField()
    optPrdTpNm = models.TextField(max_length=255)
    orderAmount = models.IntegerField()
    ordEngnm = models.TextField(max_length=255)
    customerId = models.TextField(max_length=255)
    customerCellNum = models.TextField(max_length=255)
    customerName = models.TextField(max_length=255)
    ordSeq = models.IntegerField()
    customerCellNum2 = models.TextField(null=True, max_length=255)
    ordclmDts = models.TextField(max_length=255)
    ordclmNo = models.TextField(max_length=255)
    paidDate = models.TextField(max_length=255)
    parentClaimRequestYn = models.TextField(max_length=255)
    productNum = models.TextField(max_length=255)
    paymentMethod = models.TextField(max_length=255)
    productName = models.TextField(max_length=255)
    productNum1 = models.TextField(max_length=255)
    preUseUnitcost = models.TextField(max_length=255)
    unitPrice = models.IntegerField()
    unitSold = models.IntegerField()
    customerPhoneNum = models.TextField(max_length=255)
    recipientName = models.TextField(max_length=255)
    recipientCellNum = models.TextField(max_length=255)
    recipientIdNum = models.TextField(max_length=255)
    residentNo = models.TextField(max_length=255)
    rowNum = models.TextField(max_length=255)
    unitSoldTotal = models.TextField(max_length=255)
    specialYn = models.TextField(max_length=255)
    todayDelvYn = models.TextField(max_length=255)
    totalFee = models.TextField(max_length=255)
    totalPrice = models.TextField(max_length=255)
    totalRecCnt = models.TextField(max_length=255)
    zipAddr = models.TextField(max_length=255)
    zipAddrDoro = models.TextField(max_length=255)
    postCode = models.TextField(max_length=255)
    zipNo = models.TextField(max_length=255)
    zipNoDoro = models.TextField(max_length=255)
    mallName = models.TextField(max_length=255,default='인터파크')

    def __str__(self):
        return " 주문자 : "+self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
       ordering = ['-id']

class Esm(models.Model):
    orderDate = models.DateField()
    customerId = models.TextField(max_length=255)
    mallId = models.TextField(max_length=255)
    orderNum = models.TextField(max_length=255)
    customerName = models.TextField(max_length=255)
    productNum = models.TextField(max_length=255)
    productName = models.TextField(max_length=255)
    orderAmount = models.IntegerField()
    orderOption = models.TextField(max_length=255)
    additionalConfig = models.TextField(max_length=255)
    orderGift = models.TextField(max_length=255)
    orderGiftCode = models.TextField(max_length=255)
    orderBonus = models.TextField(max_length=255)
    orderBonusCode = models.TextField(max_length=255)
    unitPrice = models.TextField(max_length=255)
    unitSold = models.TextField(max_length=255)
    sellerCode = models.IntegerField()
    sellerDetailCode = models.TextField(max_length=255)
    customerCellNum = models.TextField(max_length=255)
    customerPhoneNum = models.TextField(max_length=255)
    recipientName = models.TextField(max_length=255)
    recipientCellNum = models.TextField(max_length=255)
    recipientPhoneNum = models.TextField(max_length=255)
    recipientCustomsInfo = models.TextField(max_length=255)
    postCode = models.IntegerField()
    recipientAddress = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    shippingFeeType = models.TextField(max_length=255)
    shippingFee = models.TextField(max_length=255)
    shippingNum = models.TextField(null=True, max_length=255)
    shippingPolicy = models.TextField(max_length=255)
    skuNum = models.TextField(max_length=255)
    deliveryStore = models.TextField(max_length=255)
    saleType = models.TextField(max_length=255)
    orderType = models.TextField(max_length=255)
    shoppingBasketNum = models.TextField(max_length=255)
    orderPaymentCompleteDate = models.TextField(max_length=255)
    shipmentDeadline = models.TextField(max_length=255)
    settlementAmount = models.TextField(max_length=255)
    serviceUsageFee = models.TextField(null=True, max_length=255)
    sellerCouponSale = models.TextField(null=True, max_length=255)
    couponAppliedAmount = models.TextField(null=True, max_length=255)
    auctionVipDiscount= models.TextField(null=True, max_length=255)
    multiplePurchasesDiscount= models.TextField(null=True, max_length=255)
    smileCash = models.TextField(null=True, max_length=255)
    sellerCash = models.TextField(max_length=255, null=True)
    affiliatedCompany = models.TextField(null=True, max_length=255)
    shopSite = models.TextField(max_length=255)
    mallName = models.TextField(max_length=255,default='ESM')

    def __str__(self):
        return " 주문자 : " + self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
        ordering = ['-id']

class Tmon(models.Model):
    check = models.TextField(max_length=255)
    optionNumber = models.TextField(max_length=255)
    orderNum = models.TextField(max_length=255)
    shippingCompany = models.TextField(max_length=255)
    shippingNum = models.TextField(max_length=255)
    expectShipDate = models.TextField(max_length=255)
    orderDeadLine = models.TextField(max_length=255)
    delayedDate = models.TextField(max_length=255)
    delayReason = models.TextField(max_length=255)
    delayReasonDetail = models.TextField(max_length=255)
    finalDelayDate = models.TextField(max_length=255)
    trackNumApplyDate = models.TextField(max_length=255)
    sellerCode = models.TextField(max_length=255)
    customerName = models.TextField(max_length=255)
    customerId = models.TextField(max_length=255)
    customerCellNum = models.TextField(max_length=255)
    productName = models.TextField(max_length=255)
    orderOption = models.TextField(max_length=255)
    unitPrice = models.IntegerField()
    orderAmount = models.IntegerField()
    unitSold = models.IntegerField()
    orderPaymentCompleteDate = models.TextField(max_length=255)
    orderRequirementsOne = models.TextField(max_length=255)
    recipientName = models.TextField(max_length=255)
    recipientCustomsInfo = models.TextField(max_length=255)
    recipientPhoneNum = models.TextField(max_length=255)
    recipientAddress = models.TextField(max_length=255)
    postCode = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    shipmentState = models.TextField(max_length=255)
    shipmentDate = models.TextField(max_length=255)
    shipmentArriveDate = models.TextField(max_length=255)
    partnerCodeOne = models.TextField(max_length=255)
    partnerCodeTwo = models.TextField(max_length=255)
    partnerCodeThree = models.TextField(max_length=255)
    partnerCodeFour = models.TextField(max_length=255)
    partnerCodeFive = models.TextField(max_length=255)
    optionNumberOne = models.TextField(max_length=255)
    remoteAreaDelivery = models.TextField(max_length=255)
    remoteAreaDeliveryFee = models.TextField(max_length=255)
    shippingFeePayment = models.TextField(max_length=255)
    shippingFee = models.IntegerField()
    shipping = models.TextField(max_length=255)
    shippingType = models.TextField(max_length=255)
    orderDate = models.DateField()
    mallName = models.TextField(max_length=255,default='티몬')

    def __str__(self):
        return " 주문자 : " + self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
        ordering = ['-id']

class Naver(models.Model):
    check = models.TextField(max_length=255)
    orderNum = models.TextField(max_length=255)
    orderDate = models.DateField()
    shopSite = models.TextField(max_length=255)
    customerName = models.TextField(max_length=255)
    customerId = models.TextField(max_length=255)
    recipientName = models.TextField(max_length=255)
    shippingState = models.TextField(max_length=255)
    orderState = models.TextField(max_length=255)
    shopMachine = models.TextField(max_length=255)
    orderTime = models.TextField(max_length=255)
    productName = models.TextField(max_length=255)
    producetState = models.TextField(max_length=255)
    optionInfo = models.TextField(max_length=255)
    optionSellerCode = models.TextField(max_length=255)
    orderAmount = models.IntegerField()
    optionPrce = models.IntegerField()
    unitNormalPrice = models.IntegerField()
    saleAmount = models.IntegerField()
    sellerSaleAmount = models.IntegerField()
    unitPrice = models.IntegerField()
    gift = models.TextField(max_length=255)
    shipmentDeadline = models.TextField(max_length=255)
    shippingFeeType = models.TextField(max_length=255)
    shippingFeeSate = models.TextField(max_length=255)
    shippingFee = models.TextField(max_length=255)
    remoteAreaDeliveryFee = models.IntegerField()
    shippingSale = models.IntegerField()
    sellerCode = models.IntegerField()
    customerCellNum = models.TextField(max_length=255)
    recipientAddress = models.TextField(max_length=255)
    customerPhoneNum = models.TextField(max_length=255)
    postCode = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    payType = models.TextField(max_length=255)
    shopMarket = models.TextField(max_length=255)
    searchType = models.TextField(max_length=255)
    mallName = models.TextField(max_length=255,default='네이버')

    def __str__(self):
        return " 주문자 : " + self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
        ordering = ['-id']


class Wemap(models.Model):
    addShipPrice = models.TextField(max_length=255)
    recipientAddress1 = models.TextField(max_length=255)
    recipientAddress2 = models.TextField(max_length=255)
    addrInfo = models.TextField(max_length=255)
    allCount = models.TextField(max_length=255)
    shippingNum = models.TextField(max_length=255)
    bundleShipMethod = models.TextField(max_length=255)
    customerName = models.TextField(max_length=255)
    customerCellNum = models.TextField(max_length=255)
    claimBundleNo = models.TextField(max_length=255)
    commissionPriceTotal = models.TextField(max_length=255)
    companyCd = models.TextField(max_length=255)
    companyNm = models.TextField(max_length=255)
    orderPaymentCompleteDate = models.TextField(max_length=255)
    confirmDt = models.TextField(max_length=255)
    d4MaskingYn = models.TextField(max_length=255)
    delayShipCd = models.TextField(max_length=255)
    delayShipDt = models.TextField(max_length=255)
    delayShipMessage = models.TextField(max_length=255)
    delayShipNm = models.TextField(max_length=255)
    failCount = models.TextField(max_length=255)
    failList = models.TextField(max_length=255)
    failMessage = models.TextField(max_length=255)
    invoiceNo = models.TextField(max_length=255)
    isReply = models.TextField(max_length=255)
    isSupportWmpCommission = models.TextField(max_length=255)
    isSupportWmpPrice = models.TextField(max_length=255)
    issuePhone = models.TextField(max_length=255)
    maskingYn = models.TextField(max_length=255)
    orderRequirements = models.TextField(max_length=255)
    mid = models.TextField(max_length=255)
    multiShipNo = models.TextField(max_length=255)
    multiShippingYn = models.TextField(max_length=255)
    orderDate = models.DateField()
    shoppingBasketNum = models.TextField(max_length=255)
    orderOptNo = models.TextField(max_length=255)
    orderType = models.TextField(max_length=255)
    shipmentDeadline = models.TextField(max_length=255)
    shippingFee1 = models.TextField(max_length=255)
    partDeliveryYn = models.TextField(max_length=255)
    partnerId = models.TextField(max_length=255)
    recipientCustomsInfo = models.TextField(max_length=255)
    recipientCellNum = models.TextField(max_length=255)
    prepaymentYn = models.TextField(max_length=255)
    shippingFeeType = models.TextField(max_length=255)
    productName = models.TextField(max_length=255)
    orderNum = models.TextField(max_length=255)
    unitPrice = models.TextField(max_length=255)
    orderAmount = models.TextField(max_length=255)
    purchaseNo = models.TextField(max_length=255)
    recipientName = models.TextField(max_length=255)
    requestChannel = models.TextField(max_length=255)
    requestDate = models.TextField(max_length=255)
    requestReasonDetail = models.TextField(max_length=255)
    requestReasonType = models.TextField(max_length=255)
    requestReasonTypeNm = models.TextField(max_length=255)
    scheduleShipDt = models.TextField(max_length=255)
    sellerOptCd = models.TextField(max_length=255)
    sellerCode = models.IntegerField()
    shipAddrNo = models.TextField(max_length=255)
    shipAreaType = models.TextField(max_length=255)
    shipCompleteDt = models.TextField(max_length=255)
    shipMethod = models.TextField(max_length=255)
    shipMethodNm = models.TextField(max_length=255)
    shipNo = models.TextField(max_length=255)
    shippingFee = models.IntegerField()
    shipStatus = models.TextField(max_length=255)
    shipStatusNm = models.TextField(max_length=255)
    shippingArgumentNo = models.TextField(max_length=255)
    shippingDt = models.TextField(max_length=255)
    soptTitle = models.TextField(max_length=255)
    successCount = models.IntegerField()
    unitSold = models.IntegerField()
    uploadCode = models.TextField(max_length=255)
    uploadFailMessage = models.TextField(max_length=255)
    wmpAffiliateRate = models.TextField(max_length=255)
    postCode = models.TextField(max_length=255)
    mallName = models.TextField(max_length=255,default='위메프')

    def __str__(self):
        return " 주문자 : " + self.customerName + " 주소  : " + self.recipientAddress

    class Meta:
        ordering = ['-id']