# Generated by Django 3.2.9 on 2021-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0002_auto_20211130_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupang',
            name='mallName',
            field=models.TextField(default='쿠팡', max_length=255),
        ),
    ]
