# Generated by Django 3.2.9 on 2021-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0002_coupang_customercellnum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupang',
            name='orderNum',
            field=models.TextField(max_length=255),
        ),
    ]
