# Generated by Django 3.2.9 on 2021-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0003_coupang_mallname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('customerId', models.TextField(max_length=255)),
                ('mallId', models.TextField(max_length=255)),
                ('orderNum', models.TextField(max_length=255)),
                ('customerName', models.TextField(max_length=255)),
                ('productNum', models.TextField(max_length=255)),
                ('productName', models.TextField(max_length=255)),
                ('orderAmount', models.IntegerField()),
                ('orderOption', models.TextField(max_length=255)),
                ('additionalConfig', models.TextField(max_length=255)),
                ('orderGift', models.TextField(max_length=255)),
                ('orderGiftCode', models.TextField(max_length=255)),
                ('orderBonus', models.TextField(max_length=255)),
                ('orderBonusCode', models.TextField(max_length=255)),
                ('unitPrice', models.IntegerField()),
                ('unitSold', models.IntegerField()),
                ('sellerCode', models.IntegerField()),
                ('sellerDetailCode', models.TextField(max_length=255)),
                ('customerCellNum', models.TextField(max_length=255)),
                ('customerPhoneNum', models.TextField(max_length=255)),
                ('recipientName', models.TextField(max_length=255)),
                ('recipientCellNum', models.TextField(max_length=255)),
                ('recipientPhoneNum', models.TextField(max_length=255)),
                ('recipientCustomsInfo', models.TextField(max_length=255)),
                ('postCode', models.IntegerField()),
                ('recipientAddress', models.TextField(max_length=255)),
                ('orderRequirements', models.TextField(max_length=255)),
                ('shippingFeeType', models.TextField(max_length=255)),
                ('shippingFee', models.IntegerField()),
                ('shippingNum', models.IntegerField()),
                ('shippingPolicy', models.TextField(max_length=255)),
                ('skuNum', models.TextField(max_length=255)),
                ('deliveryStore', models.TextField(max_length=255)),
                ('saleType', models.TextField(max_length=255)),
                ('orderType', models.TextField(max_length=255)),
                ('shoppingBasketNum', models.TextField(max_length=255)),
                ('orderPaymentCompleteDate', models.TextField(max_length=255)),
                ('shipmentDeadline', models.TextField(max_length=255)),
                ('settlementAmount', models.TextField(max_length=255)),
                ('serviceUsageFee', models.IntegerField()),
                ('sellerCouponSale', models.IntegerField()),
                ('couponAppliedAmount', models.IntegerField()),
                ('auctionVipDiscount', models.IntegerField()),
                ('multiplePurchasesDiscount', models.IntegerField()),
                ('smileCash', models.IntegerField()),
                ('sellerCash', models.IntegerField()),
                ('affiliatedCompany', models.IntegerField()),
                ('shopSite', models.TextField(max_length=255)),
                ('mallName', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupang',
            options={'ordering': ['-id']},
        ),
    ]
