# Generated by Django 3.2.9 on 2021-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0003_alter_coupang_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupang',
            name='shippingBundleId',
            field=models.TextField(max_length=255),
        ),
    ]
