# Generated by Django 3.2.9 on 2021-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0004_alter_coupang_shippingbundleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupang',
            name='customerCellNum2',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
