# Generated by Django 3.2.9 on 2021-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0005_alter_coupang_customercellnum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupang',
            name='customerPhoneNum',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
