# Generated by Django 3.2.9 on 2021-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0006_alter_tmon_remoteareadeliveryfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.TextField(max_length=255)),
                ('orderNum', models.TextField(max_length=255)),
                ('orderDate', models.DateField()),
                ('shopSite', models.TextField(max_length=255)),
                ('customerName', models.TextField(max_length=255)),
                ('customerId', models.TextField(max_length=255)),
                ('recipientName', models.TextField(max_length=255)),
                ('shippingState', models.TextField(max_length=255)),
                ('orderState', models.TextField(max_length=255)),
                ('shopMachine', models.TextField(max_length=255)),
                ('orderTime', models.TextField(max_length=255)),
                ('productName', models.TextField(max_length=255)),
                ('producetState', models.TextField(max_length=255)),
                ('optionInfo', models.TextField(max_length=255)),
                ('optionSellerCode', models.TextField(max_length=255)),
                ('orderAmount', models.IntegerField()),
                ('optionPrce', models.IntegerField()),
                ('unitNormalPrice', models.IntegerField()),
                ('saleAmount', models.IntegerField()),
                ('sellerSaleAmount', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('gift', models.TextField(max_length=255)),
                ('shipmentDeadline', models.TextField(max_length=255)),
                ('shippingFeeType', models.TextField(max_length=255)),
                ('shippingFeeSate', models.TextField(max_length=255)),
                ('shippingFee', models.TextField(max_length=255)),
                ('remoteAreaDeliveryFee', models.IntegerField()),
                ('shippingSale', models.IntegerField()),
                ('sellerCode', models.IntegerField()),
                ('customerCellNum', models.TextField(max_length=255)),
                ('recipientAddress', models.TextField(max_length=255)),
                ('customerPhoneNum', models.TextField(max_length=255)),
                ('postCode', models.TextField(max_length=255)),
                ('orderRequirements', models.TextField(max_length=255)),
                ('payType', models.TextField(max_length=255)),
                ('shopMarket', models.TextField(max_length=255)),
                ('searchType', models.TextField(max_length=255)),
                ('mallName', models.TextField(default='네이버', max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
