# Generated by Django 3.2.9 on 2021-11-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0006_alter_coupang_customerphonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupang',
            name='modifiedAt',
            field=models.TextField(max_length=255),
        ),
    ]
