# Generated by Django 3.2.9 on 2021-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0008_interpark'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpark',
            name='customerCellNum2',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
