# Generated by Django 3.2.9 on 2021-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0009_alter_esm_unitsold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esm',
            name='shippingFee',
            field=models.TextField(max_length=255),
        ),
    ]
