# Generated by Django 3.2.9 on 2021-11-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0009_interpark_customercellnum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpark',
            name='serviceUsageFee',
            field=models.TextField(max_length=255),
        ),
    ]
