# Generated by Django 3.2.9 on 2021-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0011_alter_interpark_shippingfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpark',
            name='orderAmount1',
            field=models.TextField(max_length=255),
        ),
    ]
