# Generated by Django 3.2.9 on 2021-12-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0011_auto_20211201_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esm',
            old_name='sellerCas',
            new_name='sellerCash',
        ),
    ]
