# Generated by Django 3.2.9 on 2021-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0012_alter_interpark_orderamount1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpark',
            name='couponAppliedAmount',
            field=models.TextField(max_length=255),
        ),
    ]
