# Generated by Django 3.2.9 on 2021-12-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0012_rename_sellercas_esm_sellercash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpark',
            name='serviceUsageFee',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
