# Generated by Django 3.2.9 on 2021-12-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallboard', '0016_wemap_shippingfee1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpark',
            name='feeRate',
            field=models.TextField(max_length=255),
        ),
    ]
