# Generated by Django 3.2.9 on 2021-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallboard',
            name='job',
            field=models.IntegerField(),
        ),
    ]
