# Generated by Django 3.2.9 on 2021-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_mallboard_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallboard',
            name='job',
            field=models.TextField(max_length=255),
        ),
    ]
