# Generated by Django 3.2.9 on 2021-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_mallboard_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallBoardTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('job', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
                ('mySelf', models.TextField(max_length=255)),
            ],
        ),
    ]
